### ISSUE TITLE
Some things that I have to do on the current version

### ISSUE THREAD

**Issue by eric890006** [kudkudak/word-embeddings-benchmarks#24]
hi:

I noticed that in the README.rst, the command
./scripts/eval_on_all.py <path-to-file>
should changed to the latest one?
./scripts/evaluate_on_all.py -f <path-to-file> -p <format>

Also, in line 77 of scripts/evaluate_on_all.py
I added these line of code to ensure no error when running glove word embedding:
           load_kwargs = {"vocab_size": vocab_size, "dim": dim}

Lastly, can you please add the YP130 data set to the word-embedding-benchmark? thank you :)

**Comment by kudkudak** [comment]
Thanks!

I am afraid now I am not able to work on this project, but if you propose a PR, I will be more than happy to review it and merge
