### ISSUE TITLE
Outdated examples?

### ISSUE THREAD

**Issue by Lamiane** [kudkudak/word-embeddings-benchmarks#26]
Hi! I'm trying to run some examples: `python evaluate_similarity.py` and I get:
``` bash
Traceback (most recent call last):
  File "evaluate_similarity.py", line 10, in <module>
    from web.similarity import evaluate_similarity
ImportError: No module named similarity
```
Indeed module "similarity" does not exist. I'll fix the imports soon. 💪

**Comment by kudkudak** [comment]
Make sure tests pass locally on your machine (might be some are failing not because of u, but make sure the one that were passing still do)
