### ISSUE TITLE
Add fetchers for FAIR embeddings, add results to wiki/note to README.md

### ISSUE THREAD

**Issue by kudkudak** [kudkudak/word-embeddings-benchmarks#34]
See https://fasttext.cc/docs/en/pretrained-vectors.html#content

1. Add fetcher
2. https://github.com/kudkudak/word-embeddings-benchmarks/blob/dev/scripts/evaluate_embeddings.py
3. Add results of best english embedding to the wiki page https://github.com/kudkudak/word-embeddings-benchmarks/wiki
4. Add to README.md

**Comment by sobota** [comment]
Table row to wiki:
<tr>
    <th>FastText lang='en'/th>
    <td>0.734</td>
    <td>0.663</td>
    <td>0.758</td>
    <td>0.411</td>
    <td>0.351</td>
    <td>0.674</td>
    <td>0.591</td>
    <td>0.756</td>
    <td>0.001</td>
    <td>0.000</td>
    <td>0.186</td>
    <td>0.631</td>
    <td>0.795</td>
    <td>0.456</td>
    <td>0.727</td>
    <td>0.750</td>
    <td>0.644</td>
</tr>
