### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

### ISSUE THREAD

**Issue by hate5six** [kudkudak/word-embeddings-benchmarks#43]
I've generated embeddings (GloVe and word2vec) on a corpus I have and am attempting to compare their performance using evaluate_on_all.py. I'm able to run the script on the GloVe vectors but when running on the word2vec embeddings I get the following. I've checked the matrix and do not see any nans or infs. Has anyone else had this problem?

> Traceback (most recent call last):
>   File "./evaluate_on_all.py", line 83, in <module>
>     results = evaluate_on_all(w)
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/web-0.0.1-py3.5.egg/web/evaluate.py", line 409, in evaluate_on_all
>     categorization_results[name] = evaluate_categorization(w, data.X, data.y)
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/web-0.0.1-py3.5.egg/web/evaluate.py", line 98, in evaluate_categorization
>     linkage="ward").fit_predict(words[ids]))
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/scikit_learn-0.18.1-py3.5-linux-x86_64.egg/sklearn/base.py", line 410, in fit_predict
>     self.fit(X)
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/scikit_learn-0.18.1-py3.5-linux-x86_64.egg/sklearn/cluster/hierarchical.py", line 686, in fit
>     X = check_array(X, ensure_min_samples=2, estimator=self)
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/scikit_learn-0.18.1-py3.5-linux-x86_64.egg/sklearn/utils/validation.py", line 407, in check_array
>     _assert_all_finite(array)
>   File "/home/ubuntu/miniconda3/envs/attextract/lib/python3.5/site-packages/scikit_learn-0.18.1-py3.5-linux-x86_64.egg/sklearn/utils/validation.py", line 58, in _assert_all_finite
>     " or a value too large for %r." % X.dtype)
> ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
>

**Comment by kudkudak** [comment]
Closing for now. Please let me know if this is an issue still though.
