### ISSUE TITLE
Adding new datasets..

### ISSUE THREAD

**Issue by gwohlgen** [kudkudak/word-embeddings-benchmarks#71]
Hi Stanislaw and Agnieszka,

we are planning a project where we translate some of the word similarity datasets into an Asian language.
It would be nice to adopt an existing tool like yours for the evaluation of those datasets.

The question is: what is the best way to add new datasets to your tool (given that they have a similar structure like existing ones)?

It would be great if you could add information about this processes into `Readme.md` -- or add a separate description document? :)

Best, Gerhard

**Comment by gwohlgen** [comment]
Hey, thanks a lot for the quick reply, I will check it out next week :)

**Comment by kudkudak** [comment]
I will close it for now, but please let me know if u have any other questions
